FROM apache/spark:3.4.3

USER root


RUN apt-get update && \
    apt-get install -y openjdk-11-jdk maven && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH

RUN mkdir -p /opt/spark/jars/hbase

ADD https://raw.githubusercontent.com/astrolabsoftware/fink-broker/master/libs/hbase-spark-hbase2.5.8_spark3.4.3_scala2.12.0_hadoop3.3.6.jar \
    /opt/spark/jars/hbase/

ADD https://raw.githubusercontent.com/astrolabsoftware/fink-broker/master/libs/hbase-spark-protocol-shaded-hbase2.5.8_spark3.4.3_scala2.12.0_hadoop3.3.6.jar \
    /opt/spark/jars/hbase/

USER root