FROM apache/spark:3.4.3

USER root

RUN mkdir -p /opt/spark/jars/hbase

ADD https://raw.githubusercontent.com/astrolabsoftware/fink-broker/master/libs/hbase-spark-hbase2.5.8_spark3.4.3_scala2.12.0_hadoop3.3.6.jar \
    /opt/spark/jars/hbase/

ADD https://raw.githubusercontent.com/astrolabsoftware/fink-broker/master/libs/hbase-spark-protocol-shaded-hbase2.5.8_spark3.4.3_scala2.12.0_hadoop3.3.6.jar \
    /opt/spark/jars/hbase/

USER root