services:

  hadoop-hbase-cluster:
    image: massmach/hadoop-hbase-cluster:latest
    container_name: hadoop-hbase-cluster
    ports:
      - "9870:9870"   # HDFS NameNode UI
      - "8088:8088"   # YARN ResourceManager UI
      - "16010:16010" # HBase Master UI

      - "9404:9404"   # HBase RegionServer JMX Exporter
      - "9405:9405"   # HBase Master JMX Exporter
    volumes:
      - .:/workspace # mount the project code into /workspace

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    depends_on:
      - hadoop-hbase-cluster

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "472:472"
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  prometheus-data:
  grafana-data: