global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "hbase-master"
    static_configs:
      - targets: ["hadoop-hbase-cluster:9404"]
    
  - job_name: "hbase-RegionServer"
    static_configs:
      - targets: ["hadoop-hbase-cluster:9405"]